export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SINGLE_PRODUCT = "SINGLE_PRODUCT";
export const IS_AUTHENTICATED = "IS_AUTHENTICATED";
